// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_cnBcYJ4PpgVo4o0Udvx9vZAamCNvJ68',
    appId: '1:672032021608:web:fe804c95e0fbd27f006fdd',
    messagingSenderId: '672032021608',
    projectId: 'exploreease-app',
    authDomain: 'exploreease-app.firebaseapp.com',
    storageBucket: 'exploreease-app.appspot.com',
    measurementId: 'G-6SB5NRETJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrf2QoF6S4z1Y22LRAzI4sQlhouMYMAMI',
    appId: '1:672032021608:android:2b9f30b3cafcb8ea006fdd',
    messagingSenderId: '672032021608',
    projectId: 'exploreease-app',
    storageBucket: 'exploreease-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt6QpCTCnOXFyU_XkyNEL672WdE-9fsiM',
    appId: '1:672032021608:ios:363641f9520f2cdd006fdd',
    messagingSenderId: '672032021608',
    projectId: 'exploreease-app',
    storageBucket: 'exploreease-app.appspot.com',
    androidClientId: '672032021608-i2n2qa66l0bc15jh1kq2f9clt0jdv5g1.apps.googleusercontent.com',
    iosClientId: '672032021608-qamjqj5pafqb6qeulggg98aaneb55l02.apps.googleusercontent.com',
    iosBundleId: 'com.mrmihitkumar.exploreEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt6QpCTCnOXFyU_XkyNEL672WdE-9fsiM',
    appId: '1:672032021608:ios:363641f9520f2cdd006fdd',
    messagingSenderId: '672032021608',
    projectId: 'exploreease-app',
    storageBucket: 'exploreease-app.appspot.com',
    androidClientId: '672032021608-i2n2qa66l0bc15jh1kq2f9clt0jdv5g1.apps.googleusercontent.com',
    iosClientId: '672032021608-qamjqj5pafqb6qeulggg98aaneb55l02.apps.googleusercontent.com',
    iosBundleId: 'com.mrmihitkumar.exploreEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_cnBcYJ4PpgVo4o0Udvx9vZAamCNvJ68',
    appId: '1:672032021608:web:96dc8988aa602d27006fdd',
    messagingSenderId: '672032021608',
    projectId: 'exploreease-app',
    authDomain: 'exploreease-app.firebaseapp.com',
    storageBucket: 'exploreease-app.appspot.com',
    measurementId: 'G-9NMSYTN3R3',
  );

}